/* xb_runtime.cpp -- modern MSVC support glue for RXDK. */
#include <stddef.h>
#include <stdint.h>


/* -------------------------------------------------------------------------
   __ftol2_sse -- float/double to integer conversion helper generated by
   32-bit MSVC. RXDK's CRT does not provide the newer helper name.

   At entry ST(0) contains the floating-point value. fistp converts it to a
   32-bit integer and pops the x87 stack. The result is returned in EAX.
   This matches the runtime bridge used by Darkone83/OpenJazzXB.
   ------------------------------------------------------------------------- */
extern "C" long __cdecl __ftol2_sse()
{
    long result;
    __asm fistp dword ptr result
    return result;
}

// The compiler requests the bare CRT symbol __ftol2_sse, while an x86
// __cdecl function named __ftol2_sse decorates as ___ftol2_sse.
#pragma comment(linker, "/alternatename:__ftol2_sse=___ftol2_sse")

void __cdecl operator delete(void* p, unsigned int) { operator delete(p); }
void __cdecl operator delete[](void* p, unsigned int) { operator delete[](p); }

extern "C" void __cdecl __std_terminate()
{
    *((volatile unsigned int*)0) = 0xDEAD0001u;
    for (;;) {}
}

extern "C" void __cdecl __std_exception_copy(const void*, void*) {}
extern "C" void __cdecl __std_exception_destroy(void*) {}

namespace std
{
    void __cdecl _Xlength_error(const char*)
    {
        *((volatile unsigned int*)0) = 0xDEAD0002u;
        for (;;) {}
    }

    void __cdecl _Xout_of_range(const char*)
    {
        *((volatile unsigned int*)0) = 0xDEAD0003u;
        for (;;) {}
    }
}

extern "C" int __cdecl __CxxFrameHandler3(void*, void*, void*, void*)
{
    return 1;
}

extern "C" void __stdcall __ehvec_ctor(
    void* arr, unsigned int sz, unsigned int cnt,
    void (__thiscall* ctor)(void*), void (__thiscall*)(void*))
{
    unsigned char* p = (unsigned char*)arr;
    for (unsigned int i = 0; i < cnt; ++i, p += sz)
        ctor(p);
}

extern "C" void __stdcall __ehvec_dtor(
    void* arr, unsigned int sz, unsigned int cnt,
    void (__thiscall* dtor)(void*))
{
    unsigned char* p = (unsigned char*)arr + sz * cnt;
    for (unsigned int i = cnt; i > 0; --i)
    {
        p -= sz;
        dtor(p);
    }
}

#pragma comment(linker, "/alternatename:??_L@YGXPAXIIP6EX0@Z1@Z=__ehvec_ctor@20")
#pragma comment(linker, "/alternatename:??_M@YGXPAXIIP6EX0@Z@Z=__ehvec_dtor@16")

extern "C" __declspec(noreturn) void __cdecl _invoke_watson(
    const wchar_t*, const wchar_t*, const wchar_t*, unsigned int, uintptr_t)
{
    *((volatile unsigned int*)0) = 0xDEAD0004u;
    for (;;) {}
}
